language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t moshootare/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true moshootare/docker-react npm run test
